- name: "HTH | Systemd | Ensure credstore dir"
  ansible.builtin.file:
    path: "/etc/credstore.encrypted"
    state: directory
    owner: root
    group: root
    mode: 0700

- ansible.builtin.include_tasks: credential.yml
  loop: "{{ systemd.credentials }}"
  loop_control:
    loop_var: credential
