name: quality-gate

on:
  # allow manual triggering of action
  workflow_dispatch:

  # Allow other workflows to invoke this workflow
  workflow_call:

  pull_request:
    branches:
      - "main"

  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: "molecule | install"
      run: |
        pip install -U pip setuptools wheel
        pip install ansible ansible-lint molecule molecule-plugins[docker]

    - name: "molecule | test copied unit file creation"
      run: molecule  test --scenario-name create-copy-service -- --extra-vars "@../../molecule/create-template-service/input-data.yml"

    - name: "molecule | test template unit file creation"
      run: molecule  test --scenario-name create-template-service -- --extra-vars "@../../molecule/create-template-service/input-data.yml"

    - name: "molecule | test unit file state change"
      run: molecule  test --scenario-name create-template-service -- --extra-vars "@../../molecule/create-template-service/input-data.yml"

    - name: "molecule | test unit file default state values"
      run: molecule  test --scenario-name service-defaults -- --extra-vars "@../../molecule/create-template-service/input-data.yml"

    - name: "molecule | test credential encryption and file creation"
      run: molecule  test --scenario-name credentials -- --extra-vars "@../../molecule/credentials/input-data.yml"
